before:
  hooks:
    - go mod tidy
build:
  skip: true
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github
  sort: asc
  groups:
    - title: 💥 Breaking Changes
      regexp: '^.*(feat|fix|revert|refactor)(\([^)]+\))?!:'
      order: 0
    - title: ⚡ Features
      regexp: '^.*feat(\([^)]+\))?:'
      order: 1
    - title: 🪲 Bug Fixes
      regexp: '^.*fix(\([^)]+\))?:'
      order: 2
    - title: 🏎 Performance Improvements
      regexp: '^.*perf(\([^)]+\))?:'
      order: 3
    - title: ✏ Others
      order: 999
  filters:
    exclude:
      - ^build
      - ^ci
      - ^docs
      - ^style
      - ^test
